### PR TITLE
Support influxdb-ruby gem 0.2.x

### PR DESCRIPTION
**Pull request by cmjosh**
The influxdb ruby gem changed its API in the 0.2.x versions.  It looks like gem version <= 0.1.9 work with influxdb 0.8.x, but >= 0.2.0 supports only influxdb >= 0.9.0.

### CODE REVIEW

**Comment by kri5** [comment]
It seems to me that influxdb 0.9.x is not likely to be compatible with 0.8.x, and this cookbook seems to want support for both version.

I'd very much like to see 0.9.x support coming.

Do you plan to have a 0.8.x branch to maintain 0.8.x support and move to a 3.x.y cookbook version for the 0.9.x support?

**Comment by jperville** [comment]
Note that merging this will break compatibility with version 0.8 of influxdb, because influxdb gem version 0.2.x only support version 0.9 of influxdb. Choices will have to be made since version 0.2.x (which supports only version 0.9 of influxdb) and version 0.1.9 of the gem (which supports only version 0.8 of influxdb) have incompatible APIs.

**Comment by jakedavis** [comment]
In that case, the best move I think will be to do a major version bump, make a note in the CHANGELOG, and hope people upgrade safely. This PR looks good to me! Thanks @cmjosh!

**Comment by jakedavis** [comment]
Ah, maybe when merging this we should remove the attribute to flip which version of the gem you get too, since this will break compatibility anyway. I can take care of that.

**Comment by jakedavis** [comment]
Okay, hope I did it right ;) think it's okay but we'll see I guess.

**Pull request merged**
