### PR TITLE
Adding support for RPMs

### PR DESCRIPTION
**Pull request by rsr5**
I have added support for installing from RPM files.  Is this something you guys would accept upstream?  Do you need me to anything else on top of this change to get this merged?

### CODE REVIEW

**Comment by DennisBP** [comment]
:+1:

**Comment by jakedavis** [comment]
Wonderful. I just merged #45, so you'll need to merge master again, but otherwise I can get this merged. Thanks @rsr5!

**Comment by rsr5** [comment]
Ok, think I have done that now.

**Comment by jakedavis** [comment]
Thanks!

**Pull request merged**
